export const PRACTICAL_CLASS_ADD = 'PRACTICAL_CLASS_ADD';
export const PRACTICAL_CLASS_CANCEL = 'PRACTICAL_CLASS_CANCEL';



//GET_USERS: 'GET_USERS',
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'